backend:
  name: github
  repo: RomchikChan/musical-material
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "songs"
    label: "Песни"
    folder: "_songs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Название песни", name: "title", widget: "string" }
      - { label: "Год", name: "year", widget: "string" }
      - { label: "Текст песни", name: "lyrics", widget: "text" }
      - { label: "YouTube видео", name: "youtube", widget: "string", required: false }
      - label: "Инструменты"
        name: "instruments"
        widget: "list"
        fields:
          - { label: "Инструмент", name: "instrument", widget: "string" }
          - { label: "Партия", name: "part", widget: "text" }
